spring:
  main:
    web-application-type: none
  application:
    name: crime-portal-gateway-client
  logging:
    level:
      org.springframework.web: INFO
      org.springframework.ws.client.MessageTracing.sent: DEBUG
      org.springframework.ws.client.MessageTracing.received: TRACE
      org.springframework.ws.server.MessageTracing: TRACE

soap:
  encrypt-payload: true
  action: externalDocument

ws-sec:
  request-encryption-parts: "{Content}{http://www.w3.org/2003/05/soap-envelope}Body"
  actions: "Signature Encrypt"
  keystore-file: client.jks

private-key-alias-name: client
trusted-cert-alias-name: server-public

