spring:
  main:
    web-application-type: none

encryption-parts: "{Content}{http://www.justice.gov.uk/magistrates/external/ExternalDocumentRequest}ExternalDocumentRequest"
soap-default-uri: "http://localhost:8080/crime-portal-gateway/ws"
keystore-password: changeit
cert-entry-alias-name: server-public
private-key-alias-name: client
actions: "Signature Encrypt"
