spring:
  main:
    web-application-type: none
  application:
    name: crime-portal-gateway-client
  logging:
    level:
      org.springframework.web: INFO
      org.springframework.ws.client.MessageTracing.sent: TRACE
      org.springframework.ws.client.MessageTracing.received: TRACE
      org.springframework.ws.server.MessageTracing: TRACE

soap:
  encrypt-payload: true
  default-uri: "http://localhost:8080/crime-portal-gateway/ws"

ws-sec:
  request-encryption-parts: "{Content}{http://www.justice.gov.uk/magistrates/external/ExternalDocumentRequest}ExternalDocumentRequest"
  actions: "Signature Encrypt"

private-key-alias-name: client
trusted-cert-alias-name: server-public
keystore-password: changeit